name: Weekly Roblox API Fetch

on:
  schedule:
    - cron: '0 0 * * 0'    # every Sunday at UTC midnight
  workflow_dispatch:

jobs:
  fetch-and-release:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run API fetch script
      run: python script.py

    - name: Find generated dump
      id: find_file
      run: |
        dump=$(ls version-*.json)
        tag=${dump%.json}
        echo "file=$dump" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Create or update Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.find_file.outputs.tag }}
        name: ${{ steps.find_file.outputs.tag }}
        body: |
          Automated weekly Roblox API dump  
          Generated on ${{ github.run_date }}
        files: ${{ steps.find_file.outputs.file }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
